import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css'; // Make sure Bootstrap is installed
import { ReactNode } from 'react';

interface LayoutProps {
  children: ReactNode;
}

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        {children}
      </div>
    </>
  );
}

