// src/app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css"; // Import Bootstrap CSS globally
import "./globals.css"; // Import global CSS
import BootstrapClient from "@/components/BootstrapClient"; // Import your client component

const inter = Inter({ subsets: ["latin"] });

// Metadata export should remain in server components only
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout is a server component (do not use "use client" directive here)
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Render the client-side Bootstrap logic */}
        <BootstrapClient />
        {children}
      </body>
    </html>
  );
}
